### ISSUE TITLE
Bug: menuLogin function

### ISSUE THREAD

**Issue by nabilsaragih** [nabilsaragih/KerisBow#1]
menuLogin function menjadi penyebab kegagalan compile pada main.cpp

Error yang muncul:
`C:/Users/nabil/AppData/Local/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\nabil\AppData\Local\Temp\ccxVUZgk.o:main.cpp:(.text+0x1502): undefined reference to ``menuLogin(int*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*, bool*)'
C:/Users/nabil/AppData/Local/Programs/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\nabil\AppData\Local\Temp\ccxVUZgk.o:main.cpp:(.text+0x19c9): undefined reference to ``menuLogin(int*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*, bool*)'
collect2.exe: error: ld returned 1 exit status`

respon dari copilot maupun chatgpt:
The error message you are seeing is a linker error, which means that the linker is unable to find a reference to the menuLogin function. This can happen if the function is not defined or declared properly.

Here are some things you can check:

- Make sure that the menuLogin function is defined in a source file that is being compiled and linked with your main program.
- Check that the function signature in the header file matches the function definition in the source file.
- Ensure that the header file containing the menuLogin function is included in the source file where it is being called.
- Check that the source file containing the menuLogin function is being compiled and linked with your main program.

**Comment by nabilsaragih** [comment]
Dumb

**Comment by MaulanaASetiawan** [comment]
Udah Fix cik

**Comment by nabilsaragih** [comment]
real cik
